### PR TITLE
Suggest commands based on levenshtein distance

### LINKED ISSUE #120: unknown command help
Add support for helping users with typos in command names. Like this:

```
Error: unknown command "bza"

Did you mean this?
    baz
```

This might algorithm be useful: https://en.wikipedia.org/wiki/Levenshtein_distance

### PR DESCRIPTION
**Pull request by tkrajacic**
If a command is not recognized, suggest from the available commands based on the Levenshtein distance. 

If the general approach is approved, I'll add better handling, if there is no other command to suggest for example.

Alternatively, I could create a new error type instead of repurposing `CommandError` with additional parameters.

Fixes #120

### CODE REVIEW

**Comment by tkrajacic** [comment]
If the general approach is approved, I'll add better handling, if there is no other command to suggest for example.

File: Sources/ConsoleKit/Command/Utilities.swift [hunk 1]
```diff
@@ -46,3 +46,59 @@ private extension String {
         return String(repeating: " ", count: padding) + self
     }
 }
+
+extension String {
+    /// Calculate the Levenshtein distance to another
+    /// - Parameter target: Another String
+    /// - See: https://en.wikipedia.org/wiki/Levenshtein_distance
+    func levenshteinDistance(to target: String) -> Int {
```
Comment (calebkleveter) [inline Sources/ConsoleKit/Command/Utilities.swift]: For organizational purposes, this method should probably be in a new file in the `Utilities` directory, or in the `CommandError.swift` file.

File: Sources/ConsoleKit/Command/CommandError.swift [hunk 2]
```diff
@@ -5,15 +5,34 @@ public struct CommandError: Error, CustomStringConvertible {
...
+        guard let name = name else {
+            return "\(self.identifier): \(self.reason)"
+        }
+        
+        return """
+        Error: \(self.reason)
+
+        Did you mean this?
+        
+            \(suggestions(for: name, in: self.commands).joined(separator: "\n\t"))
```
Comment (calebkleveter) [inline Sources/ConsoleKit/Command/CommandError.swift]: If the resulting array from calling `suggestions(for:in:)` is empty, we don't want the suggested command section in the error message. Instead we should probably get the suggested commands, and then if the array has 1 or more elements, then output this error message. Otherwise we can just output `Command with name '<name>' not found`.

**Comment by calebkleveter** [comment]
Overall, I like the way this is going. I personally don't have anything against adding the additional parameters to `CommandError`. I personally think it makes sense.

File: Sources/ConsoleKit/Command/CommandError.swift (hunk 2 above)
Comment (tkrajacic) [reply Sources/ConsoleKit/Command/CommandError.swift]: Absolutely, as noted in the PR

File: Sources/ConsoleKit/Command/CommandError.swift [hunk 3]
```diff
@@ -5,15 +5,51 @@ public struct CommandError: Error, CustomStringConvertible {
 
     /// See `Debuggable`.
     public let reason: String
+    
+    /// The name of the attempted command
+    private let name: String?
+    
+    /// All available commands
+    private let availableCommands: [String]
```
Comment (calebkleveter) [inline Sources/ConsoleKit/Command/CommandError.swift]: Is there a reason that these properties are marked as `private` instead of being `public`?

File: Sources/ConsoleKit/Command/CommandError.swift [hunk 4]
```diff
@@ -5,15 +5,51 @@ public struct CommandError: Error, CustomStringConvertible {
 
     /// See `Debuggable`.
     public let reason: String
+    
+    /// The name of the attempted command
+    private let name: String?
```
Comment (calebkleveter) [inline Sources/ConsoleKit/Command/CommandError.swift]: The property name here is a bit confusing. It sounds like it is the name of the error, not the attempted command. I would prefer changing it from `name` to `command`.

Comment (calebkleveter) [reply Sources/ConsoleKit/Command/CommandError.swift]: If you have a name that you like better, feel free to suggest it.

File: Sources/ConsoleKit/Command/CommandGroup.swift [hunk 5]
```diff
@@ -82,7 +82,9 @@ extension CommandGroup {
             guard let command = self.commands[name] else {
                 throw CommandError(
```
Comment (tanner0101) [inline Sources/ConsoleKit/Command/CommandGroup.swift]: I think `CommandError` should be an enum. Then we can have a case like `CommandError.notFound(name: String, available: [String])`.

Comment (tkrajacic) [reply Sources/ConsoleKit/Command/CommandGroup.swift]: I guess that makes more sense as a separate PR

**Comment by calebkleveter** [comment]
Looks good! @tanner0101 Are there any changes you want before this gets merged?

@tkrajacic According to the contribution guidelines, we let PRs [remain open for at least 24 hours](https://github.com/vapor/vapor/blob/master/Docs/maintainers.md#rules) to make suer everyone gets a chance to review it before it gets merged into master and tagged.

File: Sources/ConsoleKit/Command/CommandGroup.swift (hunk 5 above)
Comment (tkrajacic) [reply Sources/ConsoleKit/Command/CommandGroup.swift]: Done in https://github.com/vapor/console-kit/pull/122
